import { WEAPON_FAMILIES, ARMOR_ARCHETYPES, MATERIAL_TIERS } from '../../../engine/shared/data/GameConstants.js';

/**
 * Generates the localized display name for a piece of equipment.
 * @param {Object} item The equipment data object.
 * @param {Function} t Translation function.
 * @returns {String} Localized name (e.g. "Wooden Dagger +1").
 */
export function getEquipmentName(item, t) {
    if (!item) return t('ui_empty_slot');
    
    const tierName = t('tier_' + item.material) || item.material;
    
    if (item.type === 'weapon') {
        const familyName = t('family_' + item.family) || item.family;
        return `${tierName} ${familyName} +${item.level || 0}`;
    } else {
        const archName = t('archetype_' + item.archetype) || item.archetype;
        const slotName = t('slot_name_' + item.slot) || item.slot;
        return `${tierName} ${archName} ${slotName} +${item.level || 0}`;
    }
}

/**
 * Calculates primary stats generated by a piece of equipment.
 * @param {Object} item The equipment data object.
 * @returns {Object} Calculated stats bonuses.
 */
export function getEquipmentStats(item) {
    const stats = {};
    if (!item) return stats;

    const tier = MATERIAL_TIERS[item.material];
    const upgradeMult = Math.pow(1.1, item.level || 0);

    if (item.type === 'weapon') {
        const family = WEAPON_FAMILIES[item.family];
        if (family && tier) {
            const itemPower = 2 * tier.mult * upgradeMult;
            stats.strength = Math.floor(itemPower * family.dmgMult);
            if (family.spdBonus) stats.speed = family.spdBonus;
            if (family.evaBonus) stats.evasion = family.evaBonus;
            if (family.magBonus) stats.magicPower = Math.floor(family.magBonus * tier.mult * upgradeMult);
            if (family.mpCostReduction) stats.mpCostReduction = family.mpCostReduction;
        }
    } else if (item.type === 'armor') {
        const arch = ARMOR_ARCHETYPES[item.archetype];
        if (arch && tier) {
            const itemPower = 5 * tier.mult * upgradeMult;
            stats.defense = Math.floor(itemPower * arch.defMult);
            if (arch.hpMult) stats.maxHp = Math.floor(itemPower * arch.hpMult);
            if (arch.mpMult) stats.maxMp = Math.floor(itemPower * arch.mpMult);
            if (arch.magMult) stats.magicPower = Math.floor(itemPower * arch.magMult);
            if (arch.spdPenalty) stats.speed = arch.spdPenalty;
            const eva = arch.evaBonus || arch.evaPenalty || 0;
            if (eva) stats.evasion = eva;
        }
    }

    return stats;
}

/**
 * Formats a stat list into a localized display string.
 * @param {Object} item The equipment data object.
 * @param {Function} t Translation function.
 * @returns {String} Localized stat string (e.g. "+5 Defense, +10 HP").
 */
export function getFormattedStats(item, t) {
    const statsObj = getEquipmentStats(item);
    const statLines = [];
    
    if (statsObj.strength) {
        statLines.push(`+${statsObj.strength} ${t('ui_stats_power') || 'STR'}`);
    }
    if (statsObj.defense) {
        statLines.push(`+${statsObj.defense} ${t('ui_stats_defense') || 'DEF'}`);
    }
    if (statsObj.maxHp) {
        statLines.push(`+${statsObj.maxHp} ${t('ui_stats_hp') || 'HP'}`);
    }
    if (statsObj.maxMp) {
        statLines.push(`+${statsObj.maxMp} ${t('ui_stats_mp') || 'MP'}`);
    }
    if (statsObj.magicPower) {
        statLines.push(`+${statsObj.magicPower} ${t('ui_stats_magic') || 'MAG'}`);
    }
    if (statsObj.speed) {
        const sign = statsObj.speed > 0 ? '+' : '';
        statLines.push(`${sign}${statsObj.speed} ${t('ui_stats_speed') || 'SPD'}`);
    }
    if (statsObj.evasion) {
        const sign = statsObj.evasion > 0 ? '+' : '';
        statLines.push(`${sign}${statsObj.evasion}% ${t('ui_stats_evasion') || 'EVA'}`);
    }
    if (statsObj.mpCostReduction) {
        statLines.push(`-${statsObj.mpCostReduction}% ${t('ui_stats_mpreduce') || 'MP Cost'}`);
    }
    
    return statLines.join(', ') || t('ui_no_item_stats') || 'No stats modification.';
}
