export const TRANSLATIONS = {
  es: {
    today_btn: "HOY", ready: "¿Listo?", already_registered: "⚠️ Ya registrado.", start_workout: "EMPEZAR ENTRENAMIENTO", view_history: "VER HISTORIAL 📊", not_today: "HOY NO, GRACIAS", settings: "AJUSTES ⚙️", language: "Idioma", change_date: "Cambiar fecha actual", routine: "Rutina", edit_routine: "EDITAR RUTINA ✏️", local_data: "Datos locales", export_json: "EXPORTAR JSON", import_json: "IMPORTAR JSON", erase_history: "BORRAR TODO EL HISTORIAL", back: "VOLVER", back_home: "VOLVER AL INICIO", dev_alert: "Funcionalidad en desarrollo", delete_confirm: "¿Borrar historial?", next: "SIGUIENTE", finish: "FINALIZAR", goal_met: "¡OBJETIVO CUMPLIDO! 🥪", first_day: "<b>¡Primer día!</b> Mañana comparamos.", vs_previous: "<b>VS. ANTERIOR:</b><br>", time: "Tiempo", history_title: "HISTORIAL", grouped: "AGRUPADO Y COMPULSIÓN:", understood: "¡Entendido!", rest: "Descansa y nos vemos mañana.",
    "Calentamiento": "Calentamiento", "Al Fallo": "Al Fallo", "Recuperación": "Recuperación", "Lenta/Negativa": "Lenta/Negativa", "Recorrido Total": "Recorrido Total",
    "Sentadillas": "Sentadillas", "Flexiones": "Flexiones", "Dom. Espalda": "Dom. Espalda", "Dom. Bíceps": "Dom. Bíceps"
  },
  en: {
    today_btn: "TODAY", ready: "Ready?", already_registered: "⚠️ Already registered.", start_workout: "START WORKOUT", view_history: "VIEW HISTORY 📊", not_today: "NOT TODAY, THANKS", settings: "SETTINGS ⚙️", language: "Language", change_date: "Change current date", routine: "Routine", edit_routine: "EDIT ROUTINE ✏️", local_data: "Local Data", export_json: "EXPORT JSON", import_json: "IMPORT JSON", erase_history: "ERASE ALL HISTORY", back: "BACK", back_home: "BACK HOME", dev_alert: "Feature in development", delete_confirm: "Delete history?", next: "NEXT", finish: "FINISH", goal_met: "GOAL MET! 🥪", first_day: "<b>First day!</b> Tomorrow we compare.", vs_previous: "<b>VS. PREVIOUS:</b><br>", time: "Time", history_title: "HISTORY", grouped: "GROUPED AND RESULTS:", understood: "Understood!", rest: "Rest and see you tomorrow.",
    "Calentamiento": "Warmup", "Al Fallo": "To Failure", "Recuperación": "Recovery", "Lenta/Negativa": "Slow/Negative", "Recorrido Total": "Full Range",
    "Sentadillas": "Squats", "Flexiones": "Push-ups", "Dom. Espalda": "Pull-ups (Back)", "Dom. Bíceps": "Pull-ups (Biceps)"
  },
  ca: {
    today_btn: "AVUI", ready: "A punt?", already_registered: "⚠️ Ja registrat.", start_workout: "COMENÇAR ENTRENAMENT", view_history: "VEURE HISTORIAL 📊", not_today: "AVUI NO, GRÀCIES", settings: "CONFIGURACIÓ ⚙️", language: "Idioma", change_date: "Canviar data actual", routine: "Rutina", edit_routine: "EDITAR RUTINA ✏️", local_data: "Dades locals", export_json: "EXPORTAR JSON", import_json: "IMPORTAR JSON", erase_history: "ESBORRAR HISTORIAL", back: "TORNAR", back_home: "TORNAR A L'INICI", dev_alert: "En desenvolupament", delete_confirm: "Esborrar historial?", next: "SEGÜENT", finish: "FINALITZAR", goal_met: "OBJECTIU ASSOLIT! 🥪", first_day: "<b>Primer dia!</b> Demà comparem.", vs_previous: "<b>VS. ANTERIOR:</b><br>", time: "Temps", history_title: "HISTORIAL", grouped: "AGRUPAT I COMPULSIÓ:", understood: "Entès!", rest: "Descansa i ens veiem demà.",
    "Calentamiento": "Escalfament", "Al Fallo": "A la fallada", "Recuperación": "Recuperació", "Lenta/Negativa": "Lenta/Negativa", "Recorrido Total": "Recorregut Total",
    "Sentadillas": "Sentadetes", "Flexiones": "Flexions", "Dom. Espalda": "Dom. Esquena", "Dom. Bíceps": "Dom. Bíceps"
  },
  eu: {
    today_btn: "GAUR", ready: "Prest?", already_registered: "⚠️ Erregistratuta.", start_workout: "HASI ENTRENAMENDUA", view_history: "IKUSI HISTORIALA 📊", not_today: "GAUR EZ, ESKERRIK ASKO", settings: "EZARPENAK ⚙️", language: "Hizkuntza", change_date: "Aldatu data", routine: "Errutina", edit_routine: "EDITATU ERRUTINA ✏️", local_data: "Datu lokalak", export_json: "ESPORTATU JSON", import_json: "INPORTATU JSON", erase_history: "EZABATU HISTORIALA", back: "ITZULI", back_home: "HASIERARA ITZULI", dev_alert: "Garapenean", delete_confirm: "Historiala ezabatu?", next: "HURRENGOA", finish: "AMAITU", goal_met: "HELBURUA LORTUTA! 🥪", first_day: "<b>Lehen eguna!</b> Bihar konparatuko dugu.", vs_previous: "<b>VS. AURREKOA:</b><br>", time: "Denbora", history_title: "HISTORIALA", grouped: "ELKARTUTA ETA EMAITZAK:", understood: "Ulertuta!", rest: "Atseden hartu eta bihar arte.",
    "Calentamiento": "Beroketa", "Al Fallo": "Hutsegitera", "Recuperación": "Errekuperazioa", "Lenta/Negativa": "Geldoa/Negatiboa", "Recorrido Total": "Ibilbide Osoa",
    "Sentadillas": "Kokorikatzeak", "Flexiones": "Flexioak", "Dom. Espalda": "Bizkarreko Dom.", "Dom. Bíceps": "Bizezpeko Dom."
  },
  gl: {
    today_btn: "HOXE", ready: "Listo?", already_registered: "⚠️ Xa rexistrado.", start_workout: "COMEZAR ADESTRAMENTO", view_history: "VER HISTORIAL 📊", not_today: "HOXE NON, GRAZAS", settings: "AXUSTES ⚙️", language: "Idioma", change_date: "Cambiar data actual", routine: "Rutina", edit_routine: "EDITAR RUTINA ✏️", local_data: "Datos locais", export_json: "EXPORTAR JSON", import_json: "IMPORTAR JSON", erase_history: "BORRAR O HISTORIAL", back: "VOLVER", back_home: "VOLVER AO INICIO", dev_alert: "En desenvolvemento", delete_confirm: "Borrar historial?", next: "SEGUINTE", finish: "FINALIZAR", goal_met: "OBXECTIVO CUMPRIDO! 🥪", first_day: "<b>Primeiro día!</b> Mañá comparamos.", vs_previous: "<b>VS. ANTERIOR:</b><br>", time: "Tempo", history_title: "HISTORIAL", grouped: "AGRUPADO E COMPULSIÓN:", understood: "Entendido!", rest: "Descansa ata mañá.",
    "Calentamiento": "Quecemento", "Al Fallo": "Ao Fallo", "Recuperación": "Recuperación", "Lenta/Negativa": "Lenta/Negativa", "Recorrido Total": "Percorrido Total",
    "Sentadillas": "Sentadillas", "Flexiones": "Flexións", "Dom. Espalda": "Dom. Costas", "Dom. Bíceps": "Dom. Bíceps"
  }
};
